### ISSUE TITLE
mistake in Linear kernel antialiased hard clipper

### ISSUE THREAD

**Issue by JeffMcClintock** [julian-parker/DAFX-AntiAliasing#1]
Hi Julian,
I just implemented your antialiased hard clipper. The output was mostly correct, but inverted relative to the input signal. occasionally a sharp discontinuity would appear.

The first if-statement..

```
    if (abs(diff1) < 0.0000001)
        output1(i) = 0.5*HardClip(input(i));
    else
        output1(i) = (HardClip1(input(i)) - HardClip1(input(i-1)) - input(i) * (HardClip0(input(i)) - HardClip0(input(i-1))))/(diff1*diff1);
    end
```
produces a correctly clipped output on the first branch, but an inverted clipped output on the second branch.
    Since the top branch is seldom taken (at least with my sine test tone) the bug is very subtle and shows as rare occasional 'spikes' in the output signal.
    
My fix was to negate the lower branches i.e. (in C++)
    
```
			if(abs(diff1) < 0.0000001)
			{
				out = 0.5 * HardClip(history[0]);
			}
			else
			{
				out = -(HardClip1(history[0]) - HardClip1(history[1]) - history[0] * (HardClip0(history[0]) - HardClip0(history[1]))) / (diff1 * diff1);
			}

			if(abs(diff2) < 0.0000001)
			{
				out += 0.5 * HardClip(history[2]);
			}
			else
			{
				out += (HardClip1(history[1]) - HardClip1(history[2]) - history[2] * (HardClip0(history[1]) - HardClip0(history[2]))) / (diff2 * diff2);
			}

```			
I hope that is helpful,
Jeff

**Comment by julian-parker** [comment]
Hi Jeff,

Thanks, good catch! I updated the Matlab code with the correct sign. The version in the paper should be correct AFAIK. 

One other thing I noticed is that the Matlab code didn't have the final version of the ill-conditioning correction (i.e. the upper branches in the above code). You can see the final versions in equation (15) and (16) in the paper.


Best,
Julian
